package fr.salome.crochet.pattern.domain.exceptions;

public enum PatternErrorCode {
	PATTERN_NOT_FOUND,
	INVALID_VALUE,

	PATTERN_ALREADY_PUBLISHED_FOR_SALE,
	PATTERN_ALREADY_PUBLISHED_FOR_TEST,
	PATTERN_INVALID_STATE_TRANSITION,
	INVALID_INSTRUCTION_INDEX,
}